## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Печем в Суздале"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]